# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy

#企业详情
class Company(scrapy.Item):
    SiteID = scrapy.Field()
    company_id = scrapy.Field()
    Credibility = scrapy.Field()
    Licensed = scrapy.Field()
    #企业已验证
    Yan = scrapy.Field()
    #放心企业
    FangXin = scrapy.Field()
    CompanyName = scrapy.Field()
    CityName = scrapy.Field()
    AreaCode = scrapy.Field()
    Relation = scrapy.Field()
    Mobile = scrapy.Field()
    Industry = scrapy.Field()
    CompanyType = scrapy.Field()
    CompanyScale = scrapy.Field()
    CompanyAddress = scrapy.Field()
    CompanyDesc = scrapy.Field()
    CompanyUrl = scrapy.Field()
    CompanyLogoUrl = scrapy.Field()
    Email = scrapy.Field()
    PraiseRate = scrapy.Field()
    GisLongitude = scrapy.Field()
    GisLatitude = scrapy.Field()
    UserId = scrapy.Field()
    UserName = scrapy.Field()
    #增加省份与区
    ProvinceName = scrapy.Field()
    WorkArea1 = scrapy.Field()
    AreaCode1 = scrapy.Field()

#职位详情
class WebJob(scrapy.Item):
    SiteID = scrapy.Field()
    JobTitle = scrapy.Field()
    Company = scrapy.Field()
    PublishTime = scrapy.Field()
    RefreshTime = scrapy.Field()
    ClickTimes = scrapy.Field()
    JobName = scrapy.Field()
    Salary = scrapy.Field()
    Eduacation = scrapy.Field()
    Number = scrapy.Field()
    Exercise = scrapy.Field()
    SSWelfare = scrapy.Field()
    SBWelfare = scrapy.Field()
    OtherWelfare = scrapy.Field()
    JobDesc = scrapy.Field()
    Relation = scrapy.Field()
    Mobile = scrapy.Field()
    Email = scrapy.Field()
    JobAddress = scrapy.Field()
    InsertTime = scrapy.Field()
    Age = scrapy.Field()
    Sex = scrapy.Field()
    LinkID = scrapy.Field()
    JobCode = scrapy.Field()
    Require = scrapy.Field()
    Tag = scrapy.Field()
    ProvinceName = scrapy.Field()
    CityName = scrapy.Field()
    WorkArea = scrapy.Field()
    WorkArea1 = scrapy.Field()
    WorkArea2 = scrapy.Field()
    CompanyLink = scrapy.Field()
    Tag = scrapy.Field()
    JobType = scrapy.Field()
    SyncStatus = scrapy.Field()
    SrcUrl = scrapy.Field()
    GisLongitude = scrapy.Field()
    GisLatitude = scrapy.Field()
    #
    AnFmtID = scrapy.Field()
    KeyValue = scrapy.Field()
    Industry = scrapy.Field()
    CompanyType = scrapy.Field()
    CompanyScale = scrapy.Field()
    WorkArea = scrapy.Field()
    Require = scrapy.Field()
    Telphone1 = scrapy.Field()
    Telphone2 = scrapy.Field()
    Age = scrapy.Field()
    ValidDate = scrapy.Field()
    ParentName = scrapy.Field()
    EduacationValue = scrapy.Field()
    SalaryMin = scrapy.Field()
    SalaryMax = scrapy.Field()
    NumberValue = scrapy.Field()
    SexValue = scrapy.Field()
    OperStatus = scrapy.Field()
    LastModifyTime = scrapy.Field()
    AreaCode = scrapy.Field()
    PropertyTag = scrapy.Field()
    SalaryValue = scrapy.Field()
    ExerciseValue = scrapy.Field()
    Valid = scrapy.Field()
    JobWorkTime = scrapy.Field()
    JobComputerSkill = scrapy.Field()
    ForeignLanguage = scrapy.Field()
    JobFunction = scrapy.Field()
    SalaryType = scrapy.Field()
    JobRequest = scrapy.Field()
    RequirementsDesc = scrapy.Field()
    ResponsibilityDesc = scrapy.Field()
    #
    StartDate = scrapy.Field()
    EndDate = scrapy.Field()
    #
    BusinessCode = scrapy.Field()

#企业评论
class Comment(scrapy.Item):
    SiteID = scrapy.Field()
    CompanyName = scrapy.Field()
    AreaCode = scrapy.Field()
    Title = scrapy.Field()
    Time = scrapy.Field()
    Type = scrapy.Field()
    Content = scrapy.Field()
    SrcUrl = scrapy.Field()
    TotalScore = scrapy.Field()
