# -*- coding: utf-8 -*-


from scrapy import Field
from jobspider.scrapy_dao.item_dao_mysql import ItemDaoMysql


class Job(ItemDaoMysql):

    superJob = Field()
    identity_verso = Field()
    company_type = Field()
    county = Field()
    company_picture = Field()
    collected = Field()
    source = Field()
    type = Field()
    button_msg = Field()
    female_count = Field()
    password = Field()
    require_shoe_weigth = Field()
    male_count = Field()
    publish_time = Field()
    activity_id = Field()
    company_im_id = Field()
    guarantee_title = Field()
    time_tag = Field()
    id = Field()
    lat = Field()
    left_count = Field()
    user_activity_status = Field()
    require_bust = Field()
    lng = Field()
    create_time = Field()
    pay = Field()
    head_count = Field()
    telephone = Field()
    isEnd = Field()
    activity_check_comment = Field()
    apply_count = Field()
    start_time = Field()
    name = Field()
    require_height = Field()
    apart_sex = Field()
    is_pay = Field()
    check_time = Field()
    status = Field()
    require_language = Field()
    isComment = Field()
    city = Field()
    require_health_record = Field()
    claw_email = Field()
    guarantee = Field()
    identity_front = Field()
    title = Field()
    require_beltline = Field()
    top = Field()
    identity = Field()
    disturb = Field()
    company_status = Field()
    pay_type = Field()
    company_code = Field()
    urgent = Field()
    pay_form = Field()
    company_check_comment = Field()
    address = Field()
    show_telephone = Field()
    company_id = Field()
    apply = Field()
    require_info = Field()
    end_time = Field()
    confirmed_count = Field()
    require_cloth_weight = Field()
    post_time = Field()
    superJob_title = Field()
    money = Field()
    group_id = Field()
    require_hipline = Field()
    activity_status = Field()
    view_count = Field()
    true_view_count = Field()
    remark = Field()

    DBKey = 'GSX'
    StoreTable = 'jobdiy_job'

class Company(ItemDaoMysql):

    app_version = Field()
    city = Field()
    frozen_money = Field()
    type = Field()
    point = Field()
    accord_point = Field()
    job_count = Field()
    response_point = Field()
    disturb = Field()
    rank = Field()
    id = Field()
    hire_type = Field()
    introduction = Field()
    phone_type = Field()
    os_version = Field()
    sex = Field()
    telephone = Field()
    satisfaction_point = Field()
    post_time = Field()
    check_comment = Field()
    fans = Field()
    fans_count = Field()
    name = Field()
    recently_login_time = Field()
    attention = Field()
    zt = Field()
    status  = Field()

    DBKey = 'GSX'
    StoreTable = 'jobdiy_company'
